### ISSUE TITLE
Ajax

### ISSUE THREAD

**Issue by henneonrails** [craftbeerpi/craftbeerpi#84]
what is wrong if my interface (dashboard) does not update the temperature value? Switches (buttons) are updated. Happened both in master and dev2.2.

**Comment by Manuel83** [comment]
Make sure that JavaScript is activated in your browers. CBP is using AJAX and WebSocket connection

**Comment by henneonrails** [comment]
does not help. Checked with chrome and safari. Timer is running and updated correctly.
